/*
 * Company apps API
 *
 * A consumer/client app associated with a company entity. For more information,     see <a href=\"https://docs.apigee.com/api-platform/publish/creating-apps-surface-your-api\">Register apps and manage API keys</a>.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// CompanyApp : Company app details.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompanyApp {
    /// Output only. App family.
    #[serde(rename = "appFamily", skip_serializing_if = "Option::is_none")]
    pub app_family: Option<String>,
    /// Output only. ID of the app.
    #[serde(rename = "appId", skip_serializing_if = "Option::is_none")]
    pub app_id: Option<String>,
    /// List of attributes used for customizing profile information or for app-specific processing. With Apigee Edge for Public Cloud, the custom attribute limit is 18.
    #[serde(rename = "attributes", skip_serializing_if = "Option::is_none")]
    pub attributes: Option<Vec<crate::models::CompanyAppAttributes>>,
    /// Callback URL used by OAuth 2.0 authorization servers to communicate authorization codes back to apps.
    #[serde(rename = "callbackUrl", skip_serializing_if = "Option::is_none")]
    pub callback_url: Option<String>,
    /// Output only. Name of the company.
    #[serde(rename = "companyName", skip_serializing_if = "Option::is_none")]
    pub company_name: Option<String>,
    /// Output only. Time the app was created in milliseconds since epoch.
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i32>,
    /// Output only. Email address of the developer that created the app.
    #[serde(rename = "createdBy", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<String>,
    /// Output only. Set of credentials for the app. Credentials are API key/secret pairs associated with API products.
    #[serde(rename = "credentials", skip_serializing_if = "Option::is_none")]
    pub credentials: Option<Vec<crate::models::CompanyAppCredentials>>,
    /// Output only. Last modified time as milliseconds since epoch.
    #[serde(rename = "lastModifiedAt", skip_serializing_if = "Option::is_none")]
    pub last_modified_at: Option<i32>,
    /// Output only. Email of developer that last modified the app.
    #[serde(rename = "lastModifiedBy", skip_serializing_if = "Option::is_none")]
    pub last_modified_by: Option<String>,
    /// Name of the company app. Required when creating a company app; not required when updating a company app. The name becomes the unique ID of the app for this organization and company. Names must begin with an alphanumeric character and can contain letters, numbers, spaces, and the following characters: `. _ # - $ %`. While you can use spaces in the name, we recommend that you use camel case, underscores, or hyphens instead. Otherwise, you will have to URL encode the app name when you need to include it in the URL of other Edge API calls.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Scopes to apply to the app. The specified scope names must already exist on the API product that you associate with the app.
    #[serde(rename = "scopes", skip_serializing_if = "Option::is_none")]
    pub scopes: Option<Vec<String>>,
    /// Status of the credential.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,
}

impl CompanyApp {
    /// Company app details.
    pub fn new() -> CompanyApp {
        CompanyApp {
            app_family: None,
            app_id: None,
            attributes: None,
            callback_url: None,
            company_name: None,
            created_at: None,
            created_by: None,
            credentials: None,
            last_modified_at: None,
            last_modified_by: None,
            name: None,
            scopes: None,
            status: None,
        }
    }
}


