/*
 * Developers API
 *
 * Developers must register with an organization on Apigee Edge. After they are registered, developers register their apps, choose the APIs they want to use, and receive the unique API credentials (consumer keys and secrets) needed to access your APIs.
 *
 * The version of the OpenAPI document: 1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// Developers : List of developer details.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct Developers {
    #[serde(rename = "developer", skip_serializing_if = "Option::is_none")]
    pub developer: Option<Vec<crate::models::Developer>>,
}

impl Developers {
    /// List of developer details.
    pub fn new() -> Developers {
        Developers {
            developer: None,
        }
    }
}


